//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("noochAdminNew.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported.
        /// </summary>
        public static string DISPUTE_STATUS_REPORTED {
            get {
                return ResourceManager.GetString("DISPUTE_STATUS_REPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string DISPUTE_STATUS_RESOLVED {
            get {
                return ResourceManager.GetString("DISPUTE_STATUS_RESOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Memo$.
        /// </summary>
        public static string MEMO {
            get {
                return ResourceManager.GetString("MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Cents$.
        /// </summary>
        public static string PLACEHLODER_CENTS {
            get {
                return ResourceManager.GetString("PLACEHLODER_CENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $AdminNote$.
        /// </summary>
        public static string PLACEHOLDER_ADMIN_NOTE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADMIN_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $DisputeId$.
        /// </summary>
        public static string PLACEHOLDER_DISPUTEID {
            get {
                return ResourceManager.GetString("PLACEHOLDER_DISPUTEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FirstName$.
        /// </summary>
        public static string PLACEHOLDER_FIRST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FriendFirstName$.
        /// </summary>
        public static string PLACEHOLDER_FRIEND_FIRST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_FRIEND_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FriendLastName$.
        /// </summary>
        public static string PLACEHOLDER_FRIEND_LAST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_FRIEND_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $LastName$.
        /// </summary>
        public static string PLACEHOLDER_LAST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NewUser$.
        /// </summary>
        public static string PLACEHOLDER_NEWUSER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NEWUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Password$.
        /// </summary>
        public static string PLACEHOLDER_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $PinNumber$.
        /// </summary>
        public static string PLACEHOLDER_PINNUMBER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PINNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RecipientFirstName$.
        /// </summary>
        public static string PLACEHOLDER_RECIPIENT_FIRST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_RECIPIENT_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $TransactionDate$.
        /// </summary>
        public static string PLACEHOLDER_TRANSACTION_DATE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_TRANSACTION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $TransactionId$.
        /// </summary>
        public static string PLACEHOLDER_TRANSACTION_ID {
            get {
                return ResourceManager.GetString("PLACEHOLDER_TRANSACTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Transfer_Amount$.
        /// </summary>
        public static string PLACEHOLDER_TRANSFER_AMOUNT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_TRANSFER_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string STATUS_ACTIVE {
            get {
                return ResourceManager.GetString("STATUS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string STATUS_INACTIVE {
            get {
                return ResourceManager.GetString("STATUS_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string STATUS_SUSPENDED {
            get {
                return ResourceManager.GetString("STATUS_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily_Blocked.
        /// </summary>
        public static string STATUS_TEMPORARILY_BLOCKED {
            get {
                return ResourceManager.GetString("STATUS_TEMPORARILY_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string TRANSACTION_TYPE_TRANSFER {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_TRANSFER", resourceCulture);
            }
        }
    }
}
