//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLevelAccessRight
    {
        public int id { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string MainMenu { get; set; }
        public string SubMenu { get; set; }
        public string RedirectUrl { get; set; }
    }
}
