//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALT
    {
        public int Id { get; set; }
        public Nullable<long> ent_num { get; set; }
        public Nullable<long> alt_num { get; set; }
        public string alt_type { get; set; }
        public string alt_name { get; set; }
        public string Country { get; set; }
    }
}
