//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankPicture
    {
        public System.Guid BankPictureId { get; set; }
        public byte[] BankPicture1 { get; set; }
        public string RoutingNumber { get; set; }
        public string BankName { get; set; }
    }
}
