//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnoxAccountDetail
    {
        public System.Guid AccountId { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string TransId { get; set; }
        public string UserKey { get; set; }
        public string UserPass { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string BankName { get; set; }
        public string AccountNum { get; set; }
        public string BankImageURL { get; set; }
        public string Status { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
