//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanlordAppInterestedEmail
    {
        public int Id { get; set; }
        public string eMail { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
    }
}
