//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberTargusReportEntity
    {
        public System.Guid MemberId { get; set; }
        public string Nooch_Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Status { get; set; }
        public Nullable<int> EmailId { get; set; }
        public Nullable<int> RecoveryEmail { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public Nullable<int> Address { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string TotalRows { get; set; }
    }
}
