//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MostFrequentFriendsTemp
    {
        public int Id { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string SenderId { get; set; }
        public string RecepientId { get; set; }
    }
}
