//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferalCodeRequest
    {
        public int RefCodeId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public Nullable<bool> IsCodeSent { get; set; }
    }
}
