//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDN
    {
        public long ent_num { get; set; }
        public string SDN_Name { get; set; }
        public string SDN_Type { get; set; }
        public string Program { get; set; }
        public string Title { get; set; }
        public string Call_Sign { get; set; }
        public string Vess_Type { get; set; }
        public string Tonnage { get; set; }
        public string GRT { get; set; }
        public string Vess_Flag { get; set; }
        public string Vess_Owner { get; set; }
        public string Remarks { get; set; }
    }
}
