//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDNSearchResult
    {
        public int ent_num { get; set; }
        public string SDN_NAME { get; set; }
        public string LastName { get; set; }
        public string SubText { get; set; }
        public string LastText { get; set; }
        public Nullable<int> subper { get; set; }
        public Nullable<int> lastper { get; set; }
    }
}
