//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMediaPost
    {
        public System.Guid Id { get; set; }
        public string PostTo { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public string PostContent { get; set; }
        public Nullable<System.Guid> PostedBy { get; set; }
    }
}
