//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynapseV3CreateTransResults
    {
        public int Id { get; set; }
        public string trans_id_oid { get; set; }
        public string trans_amount { get; set; }
        public string trans_currency { get; set; }
        public string client_id { get; set; }
        public string client_name { get; set; }
        public string extra_created_on_date { get; set; }
        public string extra_process_on_date { get; set; }
        public string extra_supp_id { get; set; }
        public string synapse_fee_fee { get; set; }
        public string synapse_fee_id { get; set; }
        public string nooch_fee_fee { get; set; }
        public string nooch_fee_id { get; set; }
        public string synapse_fee_note { get; set; }
        public string nooch_fee_note { get; set; }
        public string from_user_id { get; set; }
        public string from_node_id { get; set; }
        public string from_node_nickname { get; set; }
        public string from_node_type { get; set; }
        public string recent_status_date { get; set; }
        public string recent_note { get; set; }
        public string recent_status { get; set; }
        public string recent_status_id { get; set; }
        public string to_user_id { get; set; }
        public string to_node_id { get; set; }
        public string to_node_nickname { get; set; }
        public string to_node_type { get; set; }
        public Nullable<System.DateTime> NoochTransactionDate { get; set; }
        public string NoochAdminNotes { get; set; }
        public string NoochTransactionId { get; set; }
    }
}
