//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynapseBankLoginResult
    {
        public int Id { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<bool> IsMfa { get; set; }
        public string BankAccessToken { get; set; }
        public string mfaQuestion { get; set; }
        public Nullable<bool> IsQuestionBasedAuth { get; set; }
        public Nullable<bool> IsCodeBasedAuth { get; set; }
        public string mfaMessage { get; set; }
        public string AuthType { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
