//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynapseIdVerificationQuestion
    {
        public int Id { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string QuestionSetId { get; set; }
        public string Question { get; set; }
        public string Choice1 { get; set; }
        public string Choice2 { get; set; }
        public string Choice3 { get; set; }
        public string Choice4 { get; set; }
        public string Choice5 { get; set; }
        public Nullable<int> SynpQuestionId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateResponseSent { get; set; }
        public Nullable<bool> submitted { get; set; }
        public string person_id { get; set; }
        public Nullable<int> time_limit { get; set; }
        public string Choice1Text { get; set; }
        public string Choice2Text { get; set; }
        public string Choice3Text { get; set; }
        public string Choice4Text { get; set; }
        public string Choice5Text { get; set; }
        public Nullable<int> Choice1Id { get; set; }
        public Nullable<int> Choice2Id { get; set; }
        public Nullable<int> Choice3Id { get; set; }
        public Nullable<int> Choice4Id { get; set; }
        public Nullable<int> Choice5Id { get; set; }
        public Nullable<bool> livemode { get; set; }
        public string updated_at { get; set; }
        public string score { get; set; }
        public Nullable<bool> expired { get; set; }
        public string created_at { get; set; }
        public string message { get; set; }
    }
}
