//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionReportEntity
    {
        public System.Guid TransId { get; set; }
        public string TransactionStatus { get; set; }
        public string DisputeId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public decimal Amount { get; set; }
        public string RecipientId { get; set; }
        public string UserName { get; set; }
        public string GeoLocation { get; set; }
        public string TotalRows { get; set; }
    }
}
