//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noochAdminNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsStatusAtSynapse
    {
        public int Id { get; set; }
        public string Nooch_Transaction_Id { get; set; }
        public string Transaction_oid { get; set; }
        public string status_date { get; set; }
        public string status_note { get; set; }
        public string status { get; set; }
        public string status_id { get; set; }
    }
}
